### ISSUE TITLE
Edges are drawn on top of node

### ISSUE THREAD

**Issue by keiono** [massoudTheDude/dot-app#3]
Not sure this is fixable, but edges are drawn on top of node.  If there is an option to set z-order for nodes, this might be fixed.

**Comment by massoudTheDude** [comment]
This is fixable, it is determined by the "headport" and "tailport" edge attributes

**Comment by massoudTheDude** [comment]
Sorry K, I misunderstood you. This can be fixed with the layer attribute.

I thought you were saying that edges are always drawn from the top of the node-- this is an issue as well

**Comment by massoudTheDude** [comment]
We will get to work on both. Thanks

**Comment by massoudTheDude** [comment]
Resolved via outputorder attribute
